[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  SITE_NAME = "jetflyt"
  SITE_ID = "jetflyt"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "20" }

[context.deploy-preview]
  environment = { NODE_VERSION = "20" }

[context.branch-deploy]
  environment = { NODE_VERSION = "20" }